// data format
export const hourFormat = 'HH:mm';
export const yearFormat = 'YYYY-MM-DD';

export const GET_USER_MSG_REQUEST = 'GET_USER_MSG_REQUEST';
export const GET_USER_MSG_FAIL = 'GET_USER_MSG_FAIL';
export const GET_USER_MSG_SUCCESS = 'GET_USER_MSG_SUCCESS';
// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// loginout
export const LOGOUT = 'LOGOUT';
// register
export const REG_REQUEST = 'REG_REQUEST';
export const REG_FAIL = 'REG_FAIL';
export const REG_SUCCESS = 'REG_SUCCESS';
// repassword
export const REPASSWORD_REQUEST = 'REPASSWORD_REQUEST';
export const REPASSWORD_SUCCESS = 'REPASSWORD_SUCCESS';
export const REPASSWORD_FAIL = 'REPASSWORD_FAIL';
// checktoken
export const CHECKTOKEN_REQUEST = 'CHECKTOKEN_REQUEST';
export const CHECKTOKEN_SUCCESS = 'CHECKTOKEN_SUCCESS';
export const CHECKTOKEN_FAIL = 'CHECKTOKEN_FAIL';

// updatetoken
export const UPDATE_TOKEN_REQUEST = 'UPDATE_TOKEN_REQUEST';
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_TOKEN_FAIL = 'UPDATE_TOKEN_FAIL';

// getClients
export const GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL';

export const GET_ALL_CLIENTS_REQUEST = 'GET_ALL_CLIENTS_REQUEST';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const GET_ALL_CLIENTS_FAIL = 'GET_ALL_CLIENTS_FAIL';
// get someone Client's recordslist
export const GET_CLIENT_RECORDS_REQUEST = 'GET_CLIENT_RECORDS_REQUEST';
export const GET_CLIENT_RECORDS_SUCCESS = 'GET_CLIENT_RECORDS_SUCCESS';
export const GET_CLIENT_RECORDS_FAIL = 'GET_CLIENT_RECORDS_FAIL';

// push a new record 
export const ADD_NEW_CLIENT_RECORD_REQUEST = 'ADD_NEW_CLIENT_RECORD_REQUEST';
export const ADD_NEW_CLIENT_RECORD_SUCCESS = 'ADD_NEW_CLIENT_RECORD_SUCCESS';
export const ADD_NEW_CLIENT_RECORD_FAIL = 'ADD_NEW_CLIENT_RECORD_FAIL';

// push a new record 
export const ADD_NEW_FIRM_RECORD_REQUEST = 'ADD_NEW_FIRM_RECORD_REQUEST';
export const ADD_NEW_FIRM_RECORD_SUCCESS = 'ADD_NEW_FIRM_RECORD_SUCCESS';
export const ADD_NEW_FIRM_RECORD_FAIL = 'ADD_NEW_FIRM_RECORD_FAIL';

// add new client
export const ADD_NEW_CLIENT_REQUEST = 'ADD_NEW_CLIENT_REQUEST';
export const ADD_NEW_CLIENT_SUCCESS = 'ADD_NEW_CLIENT_SUCCESS';
export const ADD_NEW_CLIENT_FAIL = 'ADD_NEW_CLIENT_FAIL';

export const ADD_NEW_CLIENT_ORDER_REQUEST = 'ADD_NEW_CLIENT_ORDER_REQUEST';
export const ADD_NEW_CLIENT_ORDER_SUCCESS = 'ADD_NEW_CLIENT_ORDER_SUCCESS';
export const ADD_NEW_CLIENT_ORDER_FAIL = 'ADD_NEW_CLIENT_ORDER_FAIL';

// update one client
export const UPDATE_ONE_CLIENT_REQUEST = 'UPDATE_ONE_CLIENT_REQUEST';
export const UPDATE_ONE_CLIENT_SUCCESS = 'UPDATE_ONE_CLIENT_SUCCESS';
export const UPDATE_ONE_CLIENT_FAIL = 'UPDATE_ONE_CLIENT_FAIL';

// delete one client
export const DELETE_ONE_CLIENT_REQUEST = 'DELETE_ONE_CLIENT_REQUEST';
export const DELETE_ONE_CLIENT_SUCCESS = 'DELETE_ONE_CLIENT_SUCCESS';
export const DELETE_ONE_CLIENT_FAIL = 'DELETE_ONE_CLIENT_FAIL';

// get firms
export const GET_FIRMS_REQUEST = 'GET_FIRMS_REQUEST';
export const GET_FIRMS_SUCCESS = 'GET_FIRMS_SUCCESS';
export const GET_FIRMS_FAIL = 'GET_FIRMS_FAIL';

export const GET_ALL_FIRMS_REQUEST = 'GET_ALL_FIRMS_REQUEST';
export const GET_ALL_FIRMS_SUCCESS = 'GET_ALL_FIRMS_SUCCESS';
export const GET_ALL_FIRMS_FAIL = 'GET_ALL_FIRMS_FAIL';

// get someone firm's recordslist
export const GET_FIRM_RECORDS_REQUEST = 'GET_FIRM_RECORDS_REQUEST';
export const GET_FIRM_RECORDS_SUCCESS = 'GET_FIRM_RECORDS_SUCCESS';
export const GET_FIRM_RECORDS_FAIL = 'GET_FIRM_RECORDS_FAIL';

// add new firm
export const ADD_NEW_FIRM_REQUEST = 'ADD_NEW_FIRM_REQUEST';
export const ADD_NEW_FIRM_SUCCESS = 'ADD_NEW_FIRM_SUCCESS';
export const ADD_NEW_FIRM_FAIL = 'ADD_NEW_FIRM_FAIL';


export const ADD_NEW_FIRM_ORDER_REQUEST = 'ADD_NEW_FIRM_ORDER_REQUEST';
export const ADD_NEW_FIRM_ORDER_SUCCESS = 'ADD_NEW_FIRM_ORDER_SUCCESS';
export const ADD_NEW_FIRM_ORDER_FAIL = 'ADD_NEW_FIRM_ORDER_FAIL';

// update one firm
export const UPDATE_ONE_FIRM_REQUEST = 'UPDATE_ONE_FIRM_REQUEST';
export const UPDATE_ONE_FIRM_SUCCESS = 'UPDATE_ONE_FIRM_SUCCESS';
export const UPDATE_ONE_FIRM_FAIL = 'UPDATE_ONE_FIRM_FAIL';

// delete one firm
export const DELETE_ONE_FIRM_REQUEST = 'DELETE_ONE_FIRM_REQUEST';
export const DELETE_ONE_FIRM_SUCCESS = 'DELETE_ONE_FIRM_SUCCESS';
export const DELETE_ONE_FIRM_FAIL = 'DELETE_ONE_FIRM_FAIL';

// get delete client
export const GET_DELETE_CLIENTS_LIST_REQUEST = 'GET_DELETE_CLIENTS_LIST_REQUEST';
export const GET_DELETE_CLIENTS_LIST_SUCCESS = 'GET_DELETE_CLIENTS_LIST_SUCCESS';
export const GET_DELETE_CLIENTS_LIST_FAIL = 'GET_DELETE_CLIENTS_LIST_FAIL';

// get update client
export const GET_UPDATE_CLIENTS_LIST_REQUEST = 'GET_UPDATE_CLIENTS_LIST_REQUEST';
export const GET_UPDATE_CLIENTS_LIST_SUCCESS = 'GET_UPDATE_CLIENTS_LIST_SUCCESS';
export const GET_UPDATE_CLIENTS_LIST_FAIL = 'GET_UPDATE_CLIENTS_LIST_FAIL';

// get delete firm
export const GET_DELETE_FIRMS_LIST_REQUEST = 'GET_DELETE_FIRMS_LIST_REQUEST';
export const GET_DELETE_FIRMS_LIST_SUCCESS = 'GET_DELETE_FIRMS_LIST_SUCCESS';
export const GET_DELETE_FIRMS_LIST_FAIL = 'GET_DELETE_FIRMS_LIST_FAIL';

// get update firm
export const GET_UPDATE_FIRMS_LIST_REQUEST = 'GET_UPDATE_FIRMS_LIST_REQUEST';
export const GET_UPDATE_FIRMS_LIST_SUCCESS = 'GET_UPDATE_FIRMS_LIST_SUCCESS';
export const GET_UPDATE_FIRMS_LIST_FAIL = 'GET_UPDATE_FIRMS_LIST_FAIL';

export const CKECK_PASS_CLIENT_REQUEST = 'CKECK_PASS_CLIENT_REQUEST';
export const CKECK_PASS_CLIENT_SUCCESS = 'CKECK_PASS_CLIENT_SUCCESS';
export const CKECK_PASS_CLIENT_FAIL = 'CKECK_PASS_CLIENT_FAIL';

export const CKECK_PASS_FIRM_REQUEST = 'CKECK_PASS_FIRM_REQUEST';
export const CKECK_PASS_FIRM_SUCCESS = 'CKECK_PASS_FIRM_SUCCESS';
export const CKECK_PASS_FIRM_FAIL = 'CKECK_PASS_FIRM_FAIL';